

SELECT TOP 10 *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER;



CREATE DATABASE  VITECH;

CREATE DATABASE HR;

CREATE OR REPLACE TABLE EMPLOYEE (
    EMPLOYEE_ID INT,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE_NUMBER VARCHAR,
    HIRE_DATE STRING,
    JOB_ID VARCHAR,
    SALARY NUMBER,
    MANAGER_ID INT,
    DEPARTMENT_ID INT
);


SELECT * FROM EMPLOYEE ;

SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER


SELECT * FROM EMPLOYEE 
ORDER BY SALARY DESC ;




select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER ;

