-- Step 1: Create a database/schema to hold the secret (if not exists)
CREATE DATABASE IF NOT EXISTS GIT_CONFIG;
CREATE SCHEMA IF NOT EXISTS GIT_CONFIG.PUBLIC;

-- Step 2: Create the secret with your GitHub PAT
CREATE OR REPLACE SECRET GIT_CONFIG.PUBLIC.GITHUB_PAT
  TYPE = PASSWORD
  USERNAME = 'vitschool92'
  PASSWORD = 'ghp_xxxxxxxxxxxxxx';

-- Step 3: Create the API integration for Git
CREATE OR REPLACE API INTEGRATION SNOW_WORK_SPACE_INT
  API_PROVIDER = GIT_HTTPS_API
  API_ALLOWED_PREFIXES = ('https://github.com/vitschool92/')
  ALLOWED_AUTHENTICATION_SECRETS = (GIT_CONFIG.PUBLIC.GITHUB_PAT)
  ENABLED = TRUE;

-- Step 4: Create the Git repository
CREATE OR REPLACE GIT REPOSITORY GIT_CONFIG.PUBLIC.SNOW_WORK_SPACE
  API_INTEGRATION = SNOW_WORK_SPACE_INT
  GIT_CREDENTIALS = GIT_CONFIG.PUBLIC.GITHUB_PAT
  ORIGIN = 'https://github.com/vitschool92/vitech-oms-snow-dbt-test.git';

-- Verify
SHOW API INTEGRATIONS;
SHOW SECRETS;
SHOW GIT REPOSITORIES;