

  select * from OMS_DEV.BRONZE.ORDERS;


 select ORDER_ID ,
       AMOUNT,
       QUANTITY,
       PROFIT
       from OMS_DEV.BRONZE.ORDERS;


 CREATE OR REPLACE VIEW OMS_DEV.GOLD.CUST_VIEW
 AS 
 select ORDER_ID ,
       AMOUNT,
       QUANTITY,
       PROFIT
       from OMS_DEV.BRONZE.ORDERS;

SHOW VIEWS ;

SELECT * FROM OMS_DEV.GOLD.CUST_VIEW;



DELETE FROM OMS_DEV.BRONZE.ORDERS WHERE PROFIT  <  8 ;




 SELECT X.EMPLOYEE_ID,
       X.FIRST_NAME,
       X.SALARY,
       X.DEPARTMENT_ID ,
       Y.DEPARTMENT_NAME 
       FROM HR.TCS.EMPLOYEES  X   INNER JOIN HR.TCS.DEPARTMENTS Y
       ON X.DEPARTMENT_ID = Y.DEPARTMENT_ID ;


CREATE OR REPLACE VIEW OMS_DEV.GOLD.EMP_DTLS_V 
AS 
 SELECT X.EMPLOYEE_ID,
       X.FIRST_NAME,
       X.SALARY,
       X.DEPARTMENT_ID ,
       Y.DEPARTMENT_NAME 
       FROM HR.TCS.EMPLOYEES  X   INNER JOIN HR.TCS.DEPARTMENTS Y
       ON X.DEPARTMENT_ID = Y.DEPARTMENT_ID ;



       SELECT * FROM OMS_DEV.GOLD.EMP_DTLS_V ;


CREATE OR REPLACE SECURE VIEW OMS_DEV.GOLD.EMP_DTLS_SV 
AS 
 SELECT X.EMPLOYEE_ID,
       X.FIRST_NAME,
       X.SALARY,
       X.DEPARTMENT_ID ,
       Y.DEPARTMENT_NAME 
       FROM HR.TCS.EMPLOYEES  X   INNER JOIN HR.TCS.DEPARTMENTS Y
       ON X.DEPARTMENT_ID = Y.DEPARTMENT_ID ;


SELECT * FROM OMS_DEV.GOLD.EMP_DTLS_SV ;





 CREATE OR REPLACE MATERIALIZED VIEW OMS_DEV.GOLD.CUST_MV
 AS 
 select ORDER_ID ,
       AMOUNT,
       QUANTITY,
       PROFIT
       from OMS_DEV.BRONZE.ORDERS;



SELECT * FROM OMS_DEV.GOLD.CUST_MV;

SHOW VIEWS ;



---------------------------------------------

-- Remove caching just to have a fair test -- Part 1

ALTER SESSION SET USE_CACHED_RESULT=FALSE; -- disable global caching
ALTER warehouse compute_wh suspend;
ALTER warehouse compute_wh resume;



-- Prepare table
CREATE OR REPLACE TRANSIENT DATABASE ORDERS;

CREATE OR REPLACE SCHEMA TPCH_SF100;

CREATE OR REPLACE TABLE TPCH_SF100.ORDERS AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS;

SELECT * FROM ORDERS LIMIT 100



-- Example statement view -- 
SELECT
YEAR(O_ORDERDATE) AS YEAR,
MAX(O_COMMENT) AS MAX_COMMENT,
MIN(O_COMMENT) AS MIN_COMMENT,
MAX(O_CLERK) AS MAX_CLERK,
MIN(O_CLERK) AS MIN_CLERK
FROM ORDERS.TPCH_SF100.ORDERS
GROUP BY YEAR(O_ORDERDATE)
ORDER BY YEAR(O_ORDERDATE);




-- Create materialized view
CREATE OR REPLACE MATERIALIZED VIEW ORDERS_MV
AS 
SELECT
YEAR(O_ORDERDATE) AS YEAR,
MAX(O_COMMENT) AS MAX_COMMENT,
MIN(O_COMMENT) AS MIN_COMMENT,
MAX(O_CLERK) AS MAX_CLERK,
MIN(O_CLERK) AS MIN_CLERK
FROM ORDERS.TPCH_SF100.ORDERS
GROUP BY YEAR(O_ORDERDATE);


SHOW MATERIALIZED VIEWS;

-- Query view
SELECT * FROM ORDERS_MV
ORDER BY YEAR;



-- UPDATE or DELETE values
UPDATE ORDERS
SET O_CLERK='Clerk#11100000' 
WHERE O_ORDERDATE='1993-01-01'





   -- Test updated data --
-- Example statement view -- 
SELECT
YEAR(O_ORDERDATE) AS YEAR,
MAX(O_COMMENT) AS MAX_COMMENT,
MIN(O_COMMENT) AS MIN_COMMENT,
MAX(O_CLERK) AS MAX_CLERK,
MIN(O_CLERK) AS MIN_CLERK
FROM ORDERS.TPCH_SF100.ORDERS
GROUP BY YEAR(O_ORDERDATE)
ORDER BY YEAR(O_ORDERDATE);



-- Query view
SELECT * FROM ORDERS_MV
ORDER BY YEAR;


SHOW MATERIALIZED VIEWS;