

SELECT * FROM EMPLOYEES ;



SELECT CURRENT_DATE() ;

SELECT SYSDATE() ;

SELECT CURRENT_TIMESTAMP() ;

SELECT CURRENT_DATABASE() ;


SELECT  5 + 5 ;


SELECT 5 ;

SELECT 'lAVANYA' || ' k' ;



SELECT * FROM HR.TCS.EMPLOYEES ;

USE HR.TCS ;

SELECT * FROM EMPLOYEES ;


SELECT $ FROM EMPLOYEES ;-- WRONG 


SELECT * FROM EMPLOYEES 
   WHERE EMPLOYEE_ID  = 110 ;


-- 1. Select all employees

SELECT * FROM EMPLOYEES ;

-- 2. Select specific columns

SELECT 
       EMPLOYEE_ID,
       FIRST_NAME,
       LAST_NAME,
       SALARY 
    FROM EMPLOYEES ;

-- 3. Filter by salary greater than a threshold 5000
SELECT EMPLOYEE_ID,FIRST_NAME,  LAST_NAME,SALARY FROM EMPLOYEES 
WHERE SALARY > 5000 ;


SELECT EMPLOYEE_ID,FIRST_NAME,  LAST_NAME,SALARY FROM EMPLOYEES 
WHERE SALARY < 5000 ;

-- 4. Sort employees by hire date (newest first)
SELECT EMPLOYEE_ID,FIRST_NAME,  LAST_NAME,SALARY,HIRE_DATE FROM EMPLOYEES 
ORDER BY HIRE_DATE  DESC ;

-- 5. Count employees per department

SELECT DEPARTMENT_ID,COUNT(*) FROM EMPLOYEES 
      GROUP BY DEPARTMENT_ID ;

-- 6. Find employees with no manager (top-le vel)

SELECT EMPLOYEE_ID,FIRST_NAME,  LAST_NAME,SALARY,HIRE_DATE FROM EMPLOYEES 
WHERE MANAGER_ID IS NULL ;


-- 7. Get top 5 highest-paid employees
SELECT TOP 5 EMPLOYEE_ID,FIRST_NAME,  LAST_NAME,SALARY FROM EMPLOYEES 
ORDER BY SALARY  DESC 


--LOWEST 

SELECT TOP 5 EMPLOYEE_ID,FIRST_NAME,  LAST_NAME,SALARY FROM EMPLOYEES 
ORDER BY SALARY  ; 

-- 8. Search employees by name pattern start with J
SELECT  EMPLOYEE_ID,FIRST_NAME,  LAST_NAME,SALARY FROM EMPLOYEES 
WHERE FIRST_NAME LIKE 'J%'

-- 9. Calculate average salary per department

SELECT DEPARTMENT_ID,AVG(SALARY) FROM EMPLOYEES 
      GROUP BY DEPARTMENT_ID ;

-- 10. Find employees hired in a specific year -- YEAR(hire_date) = 2024
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE YEAR(HIRE_DATE) = 2024;


-- 11. Find employees with salary between a range BETWEEN 40000 AND 80000
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY BETWEEN 40000 AND 80000;


-- 12. Get distinct/unique department IDs
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;


-- 13. Count employees per manager
SELECT MANAGER_ID, COUNT(*) AS DIRECT_REPORTS FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID
ORDER BY DIRECT_REPORTS DESC;


-- 14. Find the minimum and maximum salary

 SELECT MAX(SALARY) ,MIN(SALARY)  FROM EMPLOYEES ;

-- 15. Concatenate first and last name
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME, EMAIL FROM EMPLOYEES;


-- 16. Find employees hired in the last 90 days --hire_date >= DATEADD(DAY, -90, CURRENT_DATE())
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE >= DATEADD(DAY, -90, CURRENT_DATE());


-- 17. Find departments with more than 5 employees
SELECT DEPARTMENT_ID, COUNT(*) AS EMPLOYEE_COUNT FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 5;


-- 18. Select employees using IN clause for multiple departments
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (1, 2, 3);


-- 19. Calculate total salary expenditure per each department

SELECT DEPARTMENT_ID,SUM(SALARY) FROM EMPLOYEES 
      GROUP BY DEPARTMENT_ID ;



      


      